name: CI pipeline for Golang application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'

      - name: Install all the dependencies
        run: go mod tidy

      - name: Build the applicaiton
        run: go build -v ./...

  test:
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Run the test cases
        run: go test -coverprofile=coverage.out ./...

      - name: Test coverage check
        env: 
          TESTCOVERAGE_THRESHOLD: 99
        run: |
            echo "Checking test coverage"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Total test coverage: $totalCoverage%"
            echo "Desired threshold: $TESTCOVERAGE_THRESHOLD%"

            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print($1 > $2)}') )); then 
              echo "OK"
            else 
              echo "The test coverage should be greater than $TESTCOVERAGE_THRESHOLD%"
              echo "Failed"
              exit 1
            fi